language: node_js
node_js:
  - '8'

before_script:
  - yarn build
after_success:
  - npm run coverage

deploy:
  skip_cleanup: true
  provider: npm
  email: tomsputz@outlook.com
  api_key: $NPM_TOKEN
  on:
    tags: true