language: node_js
node_js:
  - '6'
  - '5'
  - '4'

before_script:
  - yarn build
after_success:
  - npm run coverage

deploy:
  provider: npm
  email: tomsputz@outlook.com
  api_key: $NPM_TOKEN
  on:
    tags: true